export const selectors = {
  productCard: '[data-testid="product-card"]',
  productImage: '[data-testid="product-image"]',
  quantityInput: '[data-testid="quantity-input"]',
  addToCartButton: '[data-testid="add-to-cart-button"]',
  cartCount: '[data-testid="cart-count"]',
  addToCartSuccessMessage: '[data-testid="add-to-cart-success"]',
  viewCartButton: '[data-testid="view-cart-button"]',
  cartItems: '[data-testid="cart-items"]',
  outOfStockMessage: '[data-testid="out-of-stock-message"]',
  originalPrice: '[data-testid="original-price"]',
  discountPrice: '[data-testid="discount-price"]',
  variantSelector: '[data-testid="variant-selector"]',
  reviewsSection: '[data-testid="reviews-section"]',
  averageRating: '[data-testid="average-rating"]',
  reviewCount: '[data-testid="review-count"]',
  maxQuantityError: '[data-testid="max-quantity-error"]',
  relatedProductsSection: '[data-testid="related-products-section"]',
  relatedProductCard: '[data-testid="related-product-card"]',
  wishlistButton: '[data-testid="wishlist-button"]',
  wishlistConfirmation: '[data-testid="wishlist-confirmation"]',
  productSpecs: '[data-testid="product-specs"]',
  networkErrorMessage: '[data-testid="network-error-message"]',
};

export const testData = {
  productPageUrl: '/product/blue-shirt',
  productName: 'Blue Shirt',
  productDescription: 'A comfortable blue shirt.',
  productPrice: '$25.99',
  validIntegerQuantity: '2',
  validDecimalQuantity: '1.5',
  invalidQuantity: '-1',
  defaultQuantity: '1',
  initialCartCount: 0,
  allowDecimalQuantities: true, // Set this based on product requirements
  maxQuantity: 10,
  availableVariants: ['Small', 'Medium', 'Large'],
};
